/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const  PLUGIN_NAME = 'linkdin_web';
  static const  PLUGIN_VERSION = '1.0.0+1';
  static const String = 'assets/.';
  static const  SEE_WHOS_HIRING = 'assets/see_whos_hiring.png';
}
